### ISSUE TITLE
bibtex-completion-display-formats dosent seem to work here with latest version

### ISSUE THREAD

**Issue by zeltak** [tmalsburg/helm-bibtex#160]
Hi, thx for bibtex-completion-display-formats , this looks really sweet :)

i did update to latest helm-bibtex today from melpa yet using this in my config

```

(setq bibtex-completion-display-formats
    '((article       . "${=has-pdf=:1}${=has-note=:1} ${=type=:3} ${year:4} ${author:36} ${title:*} ${journal:40}")
      (inbook        . "${=has-pdf=:1}${=has-note=:1} ${=type=:3} ${year:4} ${author:36} ${title:*} Chapter ${chapter:32}")
      (incollection  . "${=has-pdf=:1}${=has-note=:1} ${=type=:3} ${year:4} ${author:36} ${title:*} ${booktitle:40}")
      (inproceedings . "${=has-pdf=:1}${=has-note=:1} ${=type=:3} ${year:4} ${author:36} ${title:*} ${booktitle:40}")
      (t             . "${=has-pdf=:1}${=has-note=:1} ${=type=:3} ${year:4} ${author:36} ${title:*}")))
```

dosent seem to give me the correct view in helm-bibtex but rather the default view, see screenshot:

![ogyx](https://cloud.githubusercontent.com/assets/498410/20215106/fba90460-a81a-11e6-940e-828579b002b2.png)

am i missing something?

also how dows one define "key" (bibtex key) in the config line?

best and thx again

Z

**Comment by tmalsburg** [comment]
No, idea why you are getting the default format.  It's also strange that there is blank space on the right.  Perhaps, restart Emacs and see what happens?

Regarding the key: you can use =key= in the format string: e.g., `${=key=:14}`

**Comment by zeltak** [comment]
Hi again
im at loss. i tried to unsintall an re-install the package. i tried a simpler syntax

```
(setq bibtex-completion-display-formats
    '(
    (t  ."${=key=:14} ${author:36} ${title:*} ${year:4} ${=has-pdf=:1}${=has-note=:1} ${=type=:7}")
    ))
```

i restarted emacs yet nada, i cant get it to not use the default view

here is my full helm-bibtex config:

```
 (use-package helm-bibtex
  :ensure t
  :config

 ;;;if not installing through MELPA
 ;;;(autoload 'helm-bibtex "helm-bibtex" "" t)

 ;;; telling helm-bibtex where your bibliographies can be found:
 (setq helm-bibtex-bibliography '("/home/zeltak/org/files/Uni/papers/kloog.papers.bib" "/home/zeltak/org/files/Uni/papers/library.bib" "/home/zeltak/org/files/Uni/papers/kloog.misc.bib" ))

 ;;Specify where PDFs can be found:
 (setq helm-bibtex-library-path (list "/home/zeltak/Sync/Uni/pdf_lib/" "/home/zeltak/Sync/Uni/pdf_lib_gen/") ) 

 ;;;If the BibTeX entries have a field that specifies the full path to the PDFs, that field can also be used
 (setq helm-bibtex-pdf-field "File")

 ;;;; Note files
 (setq helm-bibtex-notes-path "/home/zeltak/org/files/Uni/papers/notes")
 (setq helm-bibtex-notes-extension ".org")

 (setq helm-bibtex-format-citation-functions
   '((org-mode      . helm-bibtex-format-citation-org-link-to-PDF)
     (latex-mode    . helm-bibtex-format-citation-cite)
     (markdown-mode . helm-bibtex-format-citation-pandoc-citeproc)
     (default       . helm-bibtex-format-citation-default)))

 ;;Fields used for searching
 (setq helm-bibtex-additional-search-fields '(tags))

 ;;;Symbols used for indicating the availability of notes and PDF files
 (setq helm-bibtex-pdf-symbol "𝍌")
 (setq helm-bibtex-notes-symbol "✎")

 ;;set default browser
 (setq helm-bibtex-browser-function
;   (lambda (url _) (start-process "qutebrowser" "*qutebrowser*" "qutebrowser" url)))
;   (lambda (url _) (start-process "firefox" "*firefox*" "firefox" url)))
   (lambda (url _) (start-process "chromium" "*chromium*" "chromium" url)))

(setq bibtex-completion-display-formats
    '(
    (t  ."${=key=:14} ${author:36} ${title:*} ${year:4} ${=has-pdf=:1}${=has-note=:1} ${=type=:7}")
    ))
  )

```

thanks again

Z

**Comment by tmalsburg** [comment]
This doesn't look like a bug but rather like a problem with your setup.  Did you check for stale .elc files?

**Comment by ericdanan** [comment]
@zeltak from your screenshot I wonder if you aren't also loading org-ref with the org-ref-helm-bibtex backend. This backend redefines the function `helm-bibtex-candidates-formatter` to use a fixed display format, which is the bibtex-completion default format with a 31-character width column on the right for the keywords (taken out of the title column). Hence it ignores the new variable `helm-bibtex-display-formats`. You could try to not load org-ref to see if that is indeed the issue.

@jkitchin I think that with the new `bibtex-completion-display-formats` mechanism, you no longer need to redefine `helm-bibtex-candidates-formatter`. You should obtain the same result with:

```
(setq bibtex-completion-display-formats
  '((t . "${author:36} ${title:*} ${year:4} ${=has-pdf=:1}${=has-note=:1} ${=type=:7} ${keywords:31}")))
```

That would enable users to modify the display format, but they would have to customize this variable after org-ref-helm-bibtex` is loaded.

**Comment by jkitchin** [comment]
Thanks for the tip. Hopefully I can find some time next week to try this out!

**Comment by zeltak** [comment]
Hi @ericdanan 

yeah thats what exactly the case! thx for spotting that :) 

ill wait for @jkitchin update before i start using the new syntax

thx all

Z

**Comment by jkitchin** [comment]
I have pushed some code that uses the new display variable. It looks good!

**Comment by tmalsburg** [comment]
Thanks John.  I assumed this is solved now.  @zeltak feel free to reopen if you still experience problems.

**Comment by zeltak** [comment]
hmm @jkitchin , are these changes pushed to org-ref on melpa yet?

i update a few time org-ref from melpa over the last week and i still cant get the new views on org-bibtex

is there something i need to define in org-ref?

**Comment by jkitchin** [comment]
I guess it should be on Melpa by now. What problem are you seeing? I just tried it, and I see that the titles are apparently missing in the view the first time I try to use helm-bibtex, but the keywords show. If I set bibtex-completion-bibliography though, then run it again, the view seems correct. I am not sure why that happens, that variable is "let-set" in org-ref so it should work.

**Comment by zeltak** [comment]
Ha, i can confirm that when i load emacs initially it dosent work, yet if i eval my entire helm-bibtex config (inclduing the `bibtex-completion-bibliography` conf) it does work after that :)
very bizarre :)
let me know if you find a way to solve this and thx again!

Z
